# Generated by Django 4.2 on 2023-04-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram',
            name='userrr',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
