# Generated by Django 4.2 on 2023-04-11 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_instagram_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagram',
            name='userrr',
        ),
    ]
