# Generated by Django 4.2 on 2023-04-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_instagram_userrr'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram',
            name='followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagram',
            name='following',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
